import os
import subprocess
from pathlib import Path

# Paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
REF_GENOME = DATA_DIR / "references/genome.fa"
PROCESSED_DIR = DATA_DIR / "processed"
RESULTS_DIR = DATA_DIR / "results"
VCF_OUTPUT = RESULTS_DIR / "variants.vcf"

# Tools (Assumes conda env 'bio' is active)
BCFTOOLS = "bcftools"

def run_command(cmd):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True, executable="/bin/bash")

def run_variant_calling():
    print("🧬 Starting Variant Calling Pipeline (RNA-seq mode)...")
    
    # 1. Find BAM files
    # We will use the Sorted BAMs generated by STAR
    bam_files = sorted(list(PROCESSED_DIR.glob("*_Aligned.sortedByCoord.out.bam")))
    
    if not bam_files:
        print("❌ No BAM files found in processed directory.")
        return

    print(f"   Found {len(bam_files)} BAM files: {[b.name for b in bam_files]}")
    
    # 2. Bcftools Mpileup & Call
    # -f: reference genome
    # -m: multiallelic-caller
    # -v: variants only
    # -O v: output uncompressed VCF
    
    # Note: For RNA-seq, we should be careful about splice junctions, but for a demo, standard mpileup is fine.
    # We annotate samples with their filenames
    
    bam_input = " ".join([str(b) for b in bam_files])
    
    cmd = f"""
    {BCFTOOLS} mpileup -f {REF_GENOME} {bam_input} -a AD,DP,SP | \
    {BCFTOOLS} call -mv -O v -o {VCF_OUTPUT}
    """
    
    try:
        run_command(cmd)
        print(f"   ✅ Raw VCF generated: {VCF_OUTPUT}")
    except subprocess.CalledProcessError as e:
        print(f"   ❌ Variant calling failed: {e}")
        return

    # 3. Filter Variants (Simple Quality Filter)
    # QUAL > 20
    final_vcf = RESULTS_DIR / "variants.filtered.vcf"
    cmd_filter = f"""
    {BCFTOOLS} filter -i 'QUAL>20' {VCF_OUTPUT} > {final_vcf}
    """
    run_command(cmd_filter)
    print(f"   ✅ Filtered VCF generated: {final_vcf}")
    
    # 4. Stats
    print("\n📊 Variant Statistics:")
    run_command(f"{BCFTOOLS} stats {final_vcf} | grep 'TSTV'")

if __name__ == "__main__":
    if not os.path.exists(REF_GENOME):
        print(f"❌ Reference genome not found: {REF_GENOME}")
        exit(1)
    run_variant_calling()
